CREATE TABLE CUVE
(
    ID          VARCHAR2(255) NOT NULL,
    CAPACITE    DOUBLE PRECISION,
    REF_MAGASIN VARCHAR2(255),
    CONSTRAINT pk_cuve PRIMARY KEY (ID)
);

CREATE TABLE GRADUATION_CUVE
(
    ID      VARCHAR2(255) NOT NULL,
    ID_CUVE VARCHAR2(255),
    HAUTEUR DOUBLE PRECISION,
    VOLUME  DOUBLE PRECISION,
    CONSTRAINT pk_graduation_cuve PRIMARY KEY (ID)
);

CREATE TABLE POMPE
(
    ID      VARCHAR2(255) NOT NULL,
    LIBELLE VARCHAR2(255) NOT NULL,
    ID_CUVE VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_pompe PRIMARY KEY (ID)
);

CREATE TABLE POMPISTE
(
    ID      VARCHAR2(255) NOT NULL,
    NOM     VARCHAR2(255),
    PRENOMS VARCHAR2(255),
    SEXE    NUMBER(5),
    CONSTRAINT pk_pompiste PRIMARY KEY (ID)
);

CREATE TABLE ACHAT
(
    ID              VARCHAR2(255) NOT NULL,
    REF_FOURNISSEUR VARCHAR2(255),
    ID_CUVE         VARCHAR2(255),
    QUANTITE        DOUBLE PRECISION,
    MONTANT         DOUBLE PRECISION,
    DATY            date,
    CONSTRAINT pk_achat PRIMARY KEY (ID)
);

CREATE TABLE COMPTEUR
(
    ID          VARCHAR2(255) NOT NULL,
    ID_POMPISTE VARCHAR2(255),
    ID_POMPE    VARCHAR2(255),
    VALEUR      DOUBLE PRECISION,
    DATY        TIMESTAMP,
    CONSTRAINT pk_compteur PRIMARY KEY (ID)
);

CREATE TABLE PRELEVEMENT_CUVE
(
    ID            VARCHAR2(255) NOT NULL,
    HAUTEUR_JAUGE DOUBLE PRECISION,
    DATY          date,
    ID_POMPE      VARCHAR2(255),
    CONSTRAINT pk_prelevement_cuve PRIMARY KEY (ID)
);

CREATE TABLE VENTE
(
    ID         VARCHAR2(255) NOT NULL,
    REF_CLIENT VARCHAR2(255),
    ID_POMPE   VARCHAR2(255),
    QUANTITE   DOUBLE PRECISION,
    MONTANT    DOUBLE PRECISION,
    DATY       date,
    CONSTRAINT pk_vente PRIMARY KEY (ID)
);

ALTER TABLE POMPE
    ADD CONSTRAINT uc_pompe_id_cuve UNIQUE (ID_CUVE);

ALTER TABLE ACHAT
    ADD CONSTRAINT FK_ACHAT_ON_ID_CUVE FOREIGN KEY (ID_CUVE) REFERENCES CUVE (ID);

ALTER TABLE COMPTEUR
    ADD CONSTRAINT FK_COMPTEUR_ON_ID_POMPE FOREIGN KEY (ID_POMPE) REFERENCES POMPE (ID);

ALTER TABLE COMPTEUR
    ADD CONSTRAINT FK_COMPTEUR_ON_ID_POMPISTE FOREIGN KEY (ID_POMPISTE) REFERENCES POMPISTE (ID);

ALTER TABLE GRADUATION_CUVE
    ADD CONSTRAINT FK_GRADUATION_CUVE_ON_ID_CUVE FOREIGN KEY (ID_CUVE) REFERENCES CUVE (ID);

ALTER TABLE POMPE
    ADD CONSTRAINT FK_POMPE_ON_ID_CUVE FOREIGN KEY (ID_CUVE) REFERENCES CUVE (ID);

ALTER TABLE PRELEVEMENT_CUVE
    ADD CONSTRAINT FK_PC_ON_ID_POMPE FOREIGN KEY (ID_POMPE) REFERENCES POMPE (ID);

ALTER TABLE VENTE
    ADD CONSTRAINT FK_VENTE_ON_ID_POMPE FOREIGN KEY (ID_POMPE) REFERENCES POMPE (ID);
