CREATE SEQUENCE ID_PC_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_POMPE_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_POMPISTE_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_CUVE_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_COMPTEUR_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_VENTE_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_ACHAT_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ID_GRADUATION_CUVE_SEQ START WITH 1 INCREMENT BY 1;
