-- Insert data into CUVE table
INSERT INTO CUVE (ID, CAPACITE)
VALUES ('CUV1', 5000);
INSERT INTO CUVE (ID, CAPACITE)
VALUES ('CUV2', 10000);

INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG1', 'CUV1', 500, 100);
INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG3', 'CUV1', 7500, 200);
INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG5', 'CUV1', 1000, 300);
INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG2', 'CUV2', 1000, 200);
INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG4', 'CUV2', 5000, 400);
INSERT INTO CUVE_GRADUATION (ID, ID_CUVE, CAPACITE, HAUTEUR)
VALUES ('CG6', 'CUV2', 6000, 600);


-- Insert data into POMPE table
INSERT INTO POMPE (ID, LIBELLE, ID_CUVE)
VALUES ('PMP1', 'Pompe 1', 'CUV1');
INSERT INTO POMPE (ID, LIBELLE, ID_CUVE)
VALUES ('PMP2', 'Pompe 2', 'CUV2');

-- Insert data into POMPISTE table
INSERT INTO POMPISTE (ID, NOM, PRENOMS, SEXE)
VALUES ('PST1', 'Doe', 'John', 1);
INSERT INTO POMPISTE (ID, NOM, PRENOMS, SEXE)
VALUES ('PST2', 'Smith', 'Jane', 2);

-- Insert data into COMPTEUR table
INSERT INTO COMPTEUR (ID, ID_POMPISTE, ID_POMPE, VALEUR, DATY)
VALUES ('COMPT1', 'PST1', 'PMP1', 1500, TO_TIMESTAMP('2023-10-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COMPTEUR (ID, ID_POMPISTE, ID_POMPE, VALEUR, DATY)
VALUES ('COMPT2', 'PST2', 'PMP2', 3000, TO_TIMESTAMP('2023-10-02 11:00:00', 'YYYY-MM-DD HH24:MI:SS'));

