CREATE SEQUENCE compteur_perso_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE COMPTEUR_PERSO(
    ID varchar(255),
    DATY date default TRUNC(SYSDATE),
    HEURE  varchar(10),
    COMPTEUR NUMBER,
    IDPOMPISTE NUMBER,
    IDPOMPE varchar(255)
);
INSERT INTO COMPTEUR_PERSO (ID, DATY, HEURE, COMPTEUR, IDPOMPISTE, IDPOMPE)
VALUES (compteur_perso_seq.NEXTVAL, TRUNC(SYSDATE), '10:00', 100, 1, 'P001');