CREATE TABLE CUVE
(
    ID       VARCHAR2(255)    NOT NULL,
    CAPACITE DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_cuve PRIMARY KEY (ID)
);

CREATE TABLE POMPE
(
    ID      VARCHAR2(255) NOT NULL,
    LIBELLE VARCHAR2(255) NOT NULL,
    ID_CUVE VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_pompe PRIMARY KEY (ID)
);

CREATE TABLE POMPISTE
(
    ID      VARCHAR2(255) NOT NULL,
    NOM     VARCHAR2(255),
    PRENOMS VARCHAR2(255),
    SEXE    NUMBER(5),
    CONSTRAINT pk_pompiste PRIMARY KEY (ID)
);

CREATE TABLE COMPTEUR
(
    ID           VARCHAR2(255) NOT NULL,
    ID_POMPISTE  VARCHAR2(255),
    ID_POMPE     VARCHAR2(255),
    VALEUR       DOUBLE PRECISION,
    DATY       TIMESTAMP,
    CONSTRAINT pk_compteur PRIMARY KEY (ID)
);

CREATE TABLE VENTE(
    ID VARCHAR2(255) NOT NULL ,
    REF_CLIENT VARCHAR2(255),
    ID_POMPE VARCHAR2(255),
    MONTANT NUMBER(30,2),
    DATY DATE
);

ALTER TABLE POMPE
    ADD CONSTRAINT uc_pompe_id_cuve UNIQUE (ID_CUVE);

ALTER TABLE COMPTEUR
    ADD CONSTRAINT FK_COMPTEUR_ON_ID_POMPE FOREIGN KEY (ID_POMPE) REFERENCES POMPE (ID);

ALTER TABLE COMPTEUR
    ADD CONSTRAINT FK_COMPTEUR_ON_ID_POMPISTE FOREIGN KEY (ID_POMPISTE) REFERENCES POMPISTE (ID);

ALTER TABLE POMPE
    ADD CONSTRAINT FK_POMPE_ON_ID_CUVE FOREIGN KEY (ID_CUVE) REFERENCES CUVE (ID);

CREATE SEQUENCE ID_POMPE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_POMPISTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_CUVE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ID_COMPTEUR_SEQ START WITH 1 INCREMENT BY 1;